name: secure_p2p_messenger
description: Prywatny komunikator E2EE z szyfrowana historia na serwerze.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.6.1
  audioplayers: ^6.8.1
  crypto: ^3.0.6
  cryptography: ^2.7.0
  desktop_drop: ^0.7.1
  file_picker: 8.3.7
  flutter_secure_storage: ^9.2.4
  local_notifier: ^0.1.6
  package_info_plus: ^9.0.1
  path_provider: ^2.1.5
  uuid: ^4.5.1
  web_socket_channel: ^3.0.1
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_windows_video: ^1.0.11
  media_kit_libs_linux: ^1.2.1
  scrollable_positioned_list: ^0.3.8
  media_kit_libs_android_video: ^1.3.8

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_plugin_android_lifecycle: 2.0.22

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/notification.mp3
